from flask import Blueprint, request, jsonify, send_file
from app.analyzer import CodeAnalyzer
from app.github_fetcher import MAX_GITHUB_FILES, fetch_github_code
from app.ai_explainer import (
    enhance_optimizations_with_ai,
    get_ai_explanation,
    get_function_level_explanations,
)
import zipfile
import io
import os
import re

main = Blueprint('main', __name__)

MAX_ZIP_BYTES = 8 * 1024 * 1024
MAX_SOURCE_BYTES = 250 * 1024
MAX_BATCH_FILES = 30
SUPPORTED_CODE_EXTENSIONS = [
    '.py', '.pyw',
    '.js', '.jsx', '.mjs', '.cjs',
    '.ts', '.tsx', '.mts', '.cts',
    '.java',
    '.cpp', '.cc', '.cxx', '.c++', '.hpp', '.hh', '.hxx', '.ipp',
    '.c', '.h',
]


def _analyze_with_extras(code, filename, concrete_inputs=None):
    local_analyzer = CodeAnalyzer()
    result = local_analyzer.analyze(code, filename, concrete_inputs)
    language = result.get('language', 'unknown')
    result['issues'] = [_issue_problem_only(issue) for issue in (result.get('issues') or [])]

    ai_discovery_result = {
        **result,
        'optimizations': [],
        'transformed_code': {'available': False, 'code': None},
    }
    enhanced_optimizations = enhance_optimizations_with_ai(ai_discovery_result, code, language)
    ai_only_optimizations = [
        opt for opt in enhanced_optimizations
        if opt.get('ai_generated') and opt.get('example')
    ]
    result['optimizations'] = ai_only_optimizations

    ai_optimization = next(
        (opt for opt in ai_only_optimizations if opt.get('ai_generated') and opt.get('example')),
        None
    )
    if ai_optimization:
        result['ai_transformed_code'] = {
            'available': True,
            'source': 'grok',
            'title': ai_optimization.get('title', 'AI Optimized Code'),
            'description': ai_optimization.get('solution') or ai_optimization.get('title', ''),
            'complexity_before': ai_optimization.get('complexity_before'),
            'complexity_after': ai_optimization.get('complexity_after'),
            'code': ai_optimization.get('example'),
            'notes': ai_optimization.get('ai_note', 'Generated by AI from analyzer-detected expensive function facts.'),
        }
        _attach_grok_solution_to_issue(result, ai_optimization)
    else:
        result['ai_transformed_code'] = {
            'available': False,
            'source': 'grok_discovery',
            'reason': (
                'Grok did not return a verified same-behavior lower-complexity rewrite '
                'for the detected expensive functions.'
            ),
        }

    result['transformed_code'] = {
        'available': False,
        'reason': 'Only Grok-discovered optimized code is displayed to users.',
        'complexity_before': result.get('time_complexity'),
        'complexity_after': 'requires_grok',
        'code': None,
    }
    result['suggestions'] = []
    result['rating'] = local_analyzer.calculate_rating(result)
    result['ai_explanation'] = get_ai_explanation(result, code, language)
    if not result.get('optimizations'):
        result['ai_explanation']['top_optimization'] = ''

    call_graph_report = local_analyzer.call_graph_analyzer.get_call_chain_report(
        code,
        local_analyzer.last_func_complexities,
        language,
        local_analyzer.last_func_own_complexities
    )
    result['call_chain_report'] = call_graph_report

    result['function_explanations'] = get_function_level_explanations(
        local_analyzer.last_func_complexities,
        call_graph_report,
        language,
        local_analyzer.last_func_complexity_details,
        code
    )

    return result


def _issue_problem_only(issue):
    cleaned = dict(issue or {})
    message = str(cleaned.get('message') or '').strip()
    parts = re.split(r'\s+(?:—|â€”|-)\s+', message, maxsplit=1)
    if len(parts) == 2 and re.match(
        r'(?i)(?:add|use|replace|consider|can be optimized|optimi[sz]e|try)\b',
        parts[1].strip()
    ):
        message = parts[0].strip()
    cleaned['message'] = message
    return cleaned


def _attach_grok_solution_to_issue(result, ai_optimization):
    if not result.get('issues') or not ai_optimization.get('example'):
        return

    solution = {
        'title': ai_optimization.get('title') or 'Grok optimized rewrite',
        'description': ai_optimization.get('solution') or ai_optimization.get('problem') or '',
        'complexity_before': ai_optimization.get('complexity_before'),
        'complexity_after': ai_optimization.get('complexity_after'),
        'code': ai_optimization.get('example'),
        'notes': ai_optimization.get('ai_note') or 'Generated by Grok from analyzer-detected expensive function facts.',
        'source': ai_optimization.get('source', 'grok'),
    }

    target_function = str(ai_optimization.get('function') or '').lower()
    selected = None
    if target_function:
        for issue in result['issues']:
            text = f"{issue.get('message', '')} {issue.get('type', '')}".lower()
            if target_function in text:
                selected = issue
                break
    if selected is None:
        selected = next(
            (issue for issue in result['issues'] if issue.get('type') == 'performance'),
            result['issues'][0],
        )
    selected['grok_solution'] = solution


def _build_batch_summary(results, source='batch'):
    analyzer = CodeAnalyzer()
    complexities = [
        item.get('result', {}).get('time_complexity')
        for item in results
        if item.get('result', {}).get('time_complexity')
    ]
    worst_time = analyzer._max_complexity(complexities) if complexities else 'O(unknown)'
    quadratic_rank = analyzer._complexity_rank(analyzer._parse_complexity_string('O(n²)'))

    languages = {}
    confidence_counts = {'high': 0, 'medium': 0, 'low': 0, 'unknown': 0}
    low_confidence_files = []
    high_complexity_files = []
    unknown_complexity_files = []
    hotspot_count = 0

    for item in results:
        filename = item.get('filename', 'Unknown File')
        result = item.get('result') or {}
        language = result.get('language', 'unknown')
        languages[language] = languages.get(language, 0) + 1

        confidence = result.get('analysis_confidence') or {}
        level = confidence.get('time', 'unknown')
        confidence_counts[level] = confidence_counts.get(level, 0) + 1
        if level in ('low', 'medium'):
            low_confidence_files.append({
                'filename': filename,
                'confidence': level,
                'reason': confidence.get('reason', ''),
            })

        complexity = result.get('time_complexity', 'O(unknown)')
        if complexity == 'O(unknown)':
            unknown_complexity_files.append(filename)
        rank = analyzer._complexity_rank(analyzer._parse_complexity_string(complexity))
        if rank >= quadratic_rank:
            high_complexity_files.append({
                'filename': filename,
                'time_complexity': complexity,
                'rating': result.get('rating', 0),
            })
        hotspot_count += len(result.get('hotspots') or [])

    max_files = MAX_BATCH_FILES if source == 'zip' else MAX_GITHUB_FILES if source == 'github' else None
    return {
        'source': source,
        'languages': languages,
        'worst_time_complexity': worst_time,
        'confidence_counts': confidence_counts,
        'needs_review_files': low_confidence_files[:10],
        'unknown_complexity_files': unknown_complexity_files[:10],
        'high_complexity_files': high_complexity_files[:10],
        'hotspot_count': hotspot_count,
        'analysis_limits': {
            'max_files': max_files,
            'max_source_bytes_per_file': MAX_SOURCE_BYTES,
            'note': 'Batch analysis summarizes selected supported files; dependency and cross-repo runtime behavior may still need review.',
        },
    }


# ─── Health check ───────────────────────────────────────────
@main.route('/', methods=['GET'])
def home():
    return jsonify({
        'status': 'CodeScope API is running',
        'version': '2.0.0',
        'endpoints': [
            '/api/analyze/code',
            '/api/analyze/inputs',
            '/api/analyze/zip',
            '/api/analyze/github'
        ]
    })


# ─── Analyze pasted code ────────────────────────────────────
@main.route('/api/analyze/code', methods=['POST'])
def analyze_code():
    try:
        data = request.get_json()
        if not data or 'code' not in data:
            return jsonify({'error': 'No code provided'}), 400

        code = data['code']
        filename = data.get('filename', 'code.py')
        concrete_inputs = (
            data.get('concrete_inputs') or
            data.get('input_values') or
            data.get('inputs')
        )

        if not code.strip():
            return jsonify({'error': 'Code is empty'}), 400

        result = _analyze_with_extras(code, filename, concrete_inputs)

        return jsonify({'success': True, 'filename': filename, 'result': result})

    except Exception as e:
        return jsonify({'error': str(e)}), 500


@main.route('/api/analyze/inputs', methods=['POST'])
def infer_inputs():
    try:
        data = request.get_json()
        if not data or 'code' not in data:
            return jsonify({'error': 'No code provided'}), 400

        code = data['code']
        filename = data.get('filename', 'code.py')
        local_analyzer = CodeAnalyzer()
        language = local_analyzer.detect_language(code, filename)
        schema = local_analyzer.infer_input_schema(code, language)
        return jsonify({'success': True, 'filename': filename, 'input_schema': schema})

    except Exception as e:
        return jsonify({'error': str(e)}), 500


# ─── Analyze ZIP file ───────────────────────────────────────
@main.route('/api/analyze/zip', methods=['POST'])
def analyze_zip():
    try:
        if 'file' not in request.files:
            return jsonify({'error': 'No file uploaded'}), 400

        file = request.files['file']
        if not file.filename.endswith('.zip'):
            return jsonify({'error': 'Please upload a .zip file'}), 400

        file_bytes = file.read(MAX_ZIP_BYTES + 1)
        if len(file_bytes) > MAX_ZIP_BYTES:
            return jsonify({'error': 'ZIP file is too large. Please upload 8 MB or less.'}), 400
        zip_buffer = io.BytesIO(file_bytes)

        results = []
        with zipfile.ZipFile(zip_buffer, 'r') as zip_ref:
            for info in zip_ref.infolist():
                if len(results) >= MAX_BATCH_FILES:
                    break
                filename = info.filename
                ext = os.path.splitext(filename)[1].lower()
                if ext not in SUPPORTED_CODE_EXTENSIONS:
                    continue
                if filename.startswith('.') or '/__pycache__/' in filename:
                    continue
                if info.file_size > MAX_SOURCE_BYTES:
                    continue

                with zip_ref.open(filename) as f:
                    try:
                        code = f.read().decode('utf-8')
                        if not code.strip():
                            continue

                        result = _analyze_with_extras(code, filename)

                        results.append({'filename': filename, 'result': result})

                    except UnicodeDecodeError:
                        continue

        if not results:
            return jsonify({'error': 'No supported code files found in ZIP'}), 400

        avg_rating = round(
            sum(r['result']['rating'] for r in results) / len(results))
        total_lines = sum(r['result']['lines_of_code'] for r in results)
        all_issues = sum(len(r['result']['issues']) for r in results)

        return jsonify({
            'success': True,
            'total_files': len(results),
            'total_lines': total_lines,
            'total_issues': all_issues,
            'average_rating': avg_rating,
            'project_summary': _build_batch_summary(results, 'zip'),
            'files': results
        })

    except Exception as e:
        return jsonify({'error': str(e)}), 500


# ─── Analyze GitHub repo ────────────────────────────────────
@main.route('/api/analyze/github', methods=['POST'])
def analyze_github():
    try:
        data = request.get_json()
        if not data or 'url' not in data:
            return jsonify({'error': 'No GitHub URL provided'}), 400

        url = data['url']
        if 'github.com' not in url:
            return jsonify({'error': 'Please provide a valid GitHub URL'}), 400

        files = fetch_github_code(url)
        if not files:
            return jsonify({'error': 'Could not fetch code from GitHub'}), 400

        results = []
        for file in files:
            result = _analyze_with_extras(file['code'], file['filename'])

            results.append({'filename': file['filename'], 'result': result})

        avg_rating = round(
            sum(r['result']['rating'] for r in results) / len(results))
        total_lines = sum(r['result']['lines_of_code'] for r in results)
        all_issues = sum(len(r['result']['issues']) for r in results)

        return jsonify({
            'success': True,
            'github_url': url,
            'total_files': len(results),
            'total_lines': total_lines,
            'total_issues': all_issues,
            'average_rating': avg_rating,
            'project_summary': _build_batch_summary(results, 'github'),
            'files': results
        })

    except Exception as e:
        return jsonify({'error': str(e)}), 500


# ─── Generate PDF Report ────────────────────────────────────
@main.route('/api/report', methods=['POST'])
def generate_report():
    try:
        data = request.get_json()
        if not data:
            return jsonify({'error': 'No data provided'}), 400

        analysis_data = data.get('analysis_data')
        report_type = data.get('report_type', 'code')

        if not analysis_data:
            return jsonify({'error': 'No analysis data provided'}), 400

        from app.report_generator import generate_pdf_report
        pdf_bytes = generate_pdf_report(analysis_data, report_type)

        return send_file(
            io.BytesIO(pdf_bytes),
            mimetype='application/pdf',
            as_attachment=True,
            download_name='codescope_report.pdf'
        )

    except Exception as e:
        return jsonify({'error': str(e)}), 500
